### ISSUE TITLE
Add authentication functionality

### ISSUE THREAD

**Issue by Mortinke** [BrianGallew/cassandra_range_repair#20]
It would be nice to add authentication functionality to nodetool like this:

cmd = [self.options.nodetool, "-h", self.options.host, "ring", "-u", self.options.username, "-pw", self.options.password]

Many Thanks!
Sebastian

**Comment by Skunnyk** [comment]
You can simulate authentication with the -n switch ( Path to nodetool ) : 
```
range_repair.py -n "/usr/bin/nodetool -u user -pw password"
```
