### ISSUE TITLE
TravisCI integration

### ISSUE THREAD

**Issue by JensRantil** [BrianGallew/cassandra_range_repair#36]
...what do you think about adding Travis CI (or other CI tool) to check pull requests?

**Comment by BrianGallew** [comment]
I think that's a fabulous idea.
I just haven't gotten around to doing it.
In my current job, we don't run repairs at all (weird, right?), so I'm not looking at stuff all the time anymore.

**Comment by JensRantil** [comment]
I'll see if I can submit a pull request for it.
