### ISSUE TITLE
the port option added requires it to be string as all options are using the join which fails

### ISSUE THREAD

**Issue by anishek** [BrianGallew/cassandra_range_repair#41]
./src/range_repair.py", line 241 called from get_host_tokens uses the self.options.port which is a int type and not string hence the " ".join(command) commands fails with port being int rather than str

**Comment by JensRantil** [comment]
Duplicate. Already reported in #37. #42 proposes a fix. Feel free to close this.

**Comment by JensRantil** [comment]
Also, workaround is to specify the port at command. That will make it a string.

**Comment by anishek** [comment]
well i fixed it in code and got it running

**Comment by JensRantil** [comment]
@anishek FYI, this bug is now fixed in the `master` branch.
