### ISSUE TITLE
Question regarding hung repair sessions.

### ISSUE THREAD

**Issue by arshdeeptinna** [BrianGallew/cassandra_range_repair#48]
How does the script handle a repair session that hangs after sucessfully repairing some part of the repair range?

**Comment by BrianGallew** [comment]
It doesn't.  Neither the script nor Cassandra keep any kind of useful state that will tell you what has or has not happened.

That said, you can run the script verbosely in dry-run mode and it'll spit out a complete list of all the nodetool range commands it would have run.  That, in turn, could be converted into a script, with the already-completed ones deleted (should be visible in your logs).

**Comment by arshdeeptinna** [comment]
Thanks!! Hopefully one day cassandra will make repairs more transparent.
